# Generated by Django 3.2.25 on 2024-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0004_auto_20240705_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
