# Generated by Django 3.2.25 on 2024-07-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0008_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['dt_created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dt_created']},
        ),
    ]
